### ISSUE TITLE
Interface Error

### ISSUE THREAD

**Issue by ekristen** [ekristen/mythboxee#1]
For unknown reasons on Windows systems only at this point the mysql library I am using throws an InterfaceError.

Known versions to be affected at this are:
- Windows XP SP3
- Windows 7 x64

If you are experiencing this error, please add a comment with the following information of your system:
1. Windows Version Plus Service Pack and 32 v 64 bit
2. Version of MythBoxee you are running.
3. Your boxee.log (this can be emailed to me personally, the MythBoxee group, or put into a pastebin someplace of your choice)
4. Version of MythTV (mythbackend --version)

**Comment by cooper76** [comment]
Here is the info. Hopefully it helps.
1. Windows 7 x64
2. 4.23.3.beta
3. http://pastebin.com/xHk8zBRa
   4.
   MythTV Version   : 26437
   MythTV Branch    : branches/release-0-23-fixes
   Network Protocol : 23056
   Library API      : 0.23.1.201000710-1
   QT Version       : 4.6.2
   Options compiled in:
   linux debug using_oss using_alsa using_pulse using_jack using_pulseoutput using_backend using_dvb using_firewire using_frontend using_glx_proc_addr_arb using_hdhomerun using_hdpvr using_iptv using_ivtv using_joystick_menu using_libudev using_lirc using_mheg using_opengl_video using_opengl_vsync using_qtdbus using_qtwebkit using_v4l using_x11 using_xrandr using_xv using_xvmc using_xvmc_vld using_xvmcw using_bindings_perl using_bindings_python using_opengl using_vdpau using_ffmpeg_threads using_libavc_5_3 using_live using_mheg

**Comment by matthewclaussen** [comment]
1. Windows Vista 32 bit
2. 4.23.3 beta
3. http://pastebin.com/hfH3PVGa
4. MythTV 0.23.1+fixes26695 from the Mythbuntu repo

**Comment by cooper76** [comment]
Just an update with my setup here, I loaded up a XP SP3 box and it connected just fine to the MythTV.  So, just my Windows 7 x64 box is having problems.

**Comment by ekristen** [comment]
I will be asking for help with this soon, I have to modify the mysql library and add some debug code to find out what sql queries are happening when it fails. When I get the modifications done I will post the new library up for use by those having the issue for testing.

**Comment by ekristen** [comment]
Download http://github.com/ekristen/mythboxee/raw/interface/mysql/connector/cursor.py and replace in your mythboxee install, then reproduce the error, I think for most of you it is just by running the app. Post logs at http://mythboxee.pastebin.com/ and then paste the links here.

**Comment by matthewclaussen** [comment]
On my Vista box. http://mythboxee.pastebin.com/HjR7miVD

**Comment by ekristen** [comment]
Opened a new ticket with the mysql library developer, hopefully he might be able to shed some light on the error message at least.

https://bugs.launchpad.net/myconnpy/+bug/661994

**Comment by cooper76** [comment]
Ok. This is weird. I went into mythboxee on my Windows 7 x64 box and tried to load it up (before putting in your new cursor.py file) and it started off as having the same issue as #6 (missing configuration settings).  So I only went out of mythboxee and then started it again and then my tv show were there and I could play them. Hmm...

**Comment by ekristen** [comment]
If you have only run boxee twice then there will be two logs, boxee.log which is the latest and boxee.log.old which will be the one before. If you can post both to http://mythboxee.pastebin.com

**Comment by cooper76** [comment]
Now after updating to 4.4.23.1.beta can't make it work like before.  For some reason I can't post to pastebin, so I'm emailing my recent log to you.

**Comment by matthewclaussen** [comment]
Updated to 4.4.23.1 beta and still have the interface error on my Vista box.
http://mythboxee.pastebin.com/Y1UgPgJj
I will test it out soon on Ubuntu 10.04.

**Comment by ekristen** [comment]
Matt, can you update your cursor.py file to http://github.com/ekristen/mythboxee/raw/interface/mysql/connector/cursor.py and re-post the log? Also if you can look at the log, see what the last query to be executed before the error is thrown, and run that manually through phpmyadmin and post the data returned that would also be helpful. Thanks.

**Comment by matthewclaussen** [comment]
Ok, I replaced cursor.py with the new one. Here is my new log.
http://mythboxee.pastebin.com/XqPc8w7A
What is it from there that you want me to check out in phpmyadmin?
I see in the error log that on line 287 it says "18:47:55 T:5268 M:1276375040  NOTICE: SELECT \* FROM recorded WHERE chanid=2140 AND starttime='2010-07-15 21:00:00'" right before the errors start to get spit back.
In that table from phpmyadmin it refers to "Futurama     The Duh-Vinci Code      The crew races to future Rome to unearth the shock...     Sitcom".

Is that what you're looking for? If not then I need you to explain what to do exactly.
Thanks for working on tracking down these errors!

**Comment by matthewclaussen** [comment]
I looked at a 2nd log and I am pretty sure that I didn't do what you asked cause the show that I thought it got hung up on kept on changing. Whenever you're ready to work on this I'm going to need some guidance on what to do.

**Comment by ekristen** [comment]
Well at this point I have no clue what the problem is, just keep posting logs here, the more I have the better I would image. Unfortunately it is no one query or no one thing that is causing the error to occur. It just happens randomly on all Windows Systems :(

**Comment by matthewclaussen** [comment]
First log with the brand new cursor file
http://mythboxee.pastebin.com/eDn9ZGhF
Second log, this time it seemed to have gone through more shows before the error happened.
http://mythboxee.pastebin.com/nkKCzVuT

And at least now its a different error. "Empty buffer" mean anything to you?

**Comment by cooper76** [comment]
I tried the new cursor.py file and got the same "Empty buffer" error.

http://mythboxee.pastebin.com/L3KPdsvy

**Comment by ekristen** [comment]
Too many changes to list. Rewrote the entire mythboxee.py file, split code into classes mainly. Closed by 4dc12973561ad015c2bb1fc959dc6b26120807d3, #2, #4, #6
