### ISSUE TITLE
Error on 4.23.2.beta

### ISSUE THREAD

**Issue by cooper76** [ekristen/mythboxee#10]
I'm getting the "Backend speaks version 23056, we speak version 56" error in this version as well.

Here is part of my log:

19:27:41 T:8476 M:715411456  NOTICE: >>> MythBoxee: def(**init**): Start =========================================================
19:27:41 T:8476 M:715411456  NOTICE: >>> MythBoxee: def(**init**): Version: 4.23.2.beta
19:27:41 T:8476 M:715411456  NOTICE: >>> MythBoxee: def(**init**): Python Version: (2, 4, 5, 'final', 0)
19:27:41 T:8476 M:715395072  NOTICE: >>> MythBoxee: def(**init**): Attempting Database Connection ...
19:27:41 T:8476 M:715341824  NOTICE: >>> MythBoxee: def(**init**): Database Connection Successful
19:27:41 T:8476 M:715300864  NOTICE: 2010-10-04 19:27:41.000 Python Backend Connection: Backend has version 23056, and we speak 56
19:27:41 T:8476 M:715309056   ERROR: Scriptresult: Error
19:27:41 T:8476 M:715309056  NOTICE: Traceback (most recent call last):
19:27:41 T:8476 M:715309056  NOTICE:   File "<string>", line 3, in ?
19:27:41 T:8476 M:715309056  NOTICE:   File "C:\Users\Eric\AppData\Roaming\BOXEE\userdata\apps\com.erikkristensen.mythboxee4\mythboxee.py", line 65, in **init**
19:27:41 T:8476 M:715304960  NOTICE: self.be = mythtv.MythBE(db=self.db)
19:27:41 T:8476 M:715304960  NOTICE:   File "C:\Users\Eric\AppData\Roaming\BOXEE\userdata\apps\com.erikkristensen.mythboxee4\mythtv\MythBase.py", line 1352, in **init**
19:27:41 T:8476 M:714883072  NOTICE: self.be = MythBEConn(backend, type, db)
19:27:41 T:8476 M:714883072  NOTICE:   File "C:\Users\Eric\AppData\Roaming\BOXEE\userdata\apps\com.erikkristensen.mythboxee4\mythtv\MythBase.py", line 1240, in **init**
19:27:42 T:8476 M:714825728  NOTICE: self.check_version()
19:27:42 T:8476 M:714825728  NOTICE:   File "C:\Users\Eric\AppData\Roaming\BOXEE\userdata\apps\com.erikkristensen.mythboxee4\mythtv\MythBase.py", line 1271, in check_version
19:27:42 T:8476 M:715968512  NOTICE: int(res[1]), PROTO_VERSION)
19:27:42 T:8476 M:715968512  NOTICE: mythtv.MythBase
19:27:42 T:8476 M:715968512  NOTICE: .
19:27:42 T:8476 M:715968512  NOTICE: MythBEError
19:27:42 T:8476 M:715968512  NOTICE: :
19:27:42 T:8476 M:715968512  NOTICE: Backend speaks version 23056, we speak version 56

**Comment by ekristen** [comment]
If you are running version 0.23.1 or later of MythTV which you are since it is looking for 23056 you will need to modify the mythstatic.py file and update the version from 56 to 23056. In the next release I will be making 23056 permanent as I probably should have for this release, but apparently I am running a version behind on my development system.

**Comment by ekristen** [comment]
Also I'll leave this issue open until I update to protocol version.
