### ISSUE TITLE
Scriptresult: Error

### ISSUE THREAD

**Issue by matthewclaussen** [ekristen/mythboxee#11]
MythBoxee seems to be able to connect to the MythTV backend but part way through the script it throws this error.

00:33:19 T:49436 M:1804828672   ERROR: Scriptresult: Error
00:33:19 T:49436 M:1804828672  NOTICE: Traceback (most recent call last):
00:33:19 T:49436 M:1804828672  NOTICE:   File "<string>", line 3, in ?
00:33:19 T:49436 M:1804828672  NOTICE:   File "C:\Users\Matthew\AppData\Roaming\BOXEE\userdata\apps\com.erikkristensen.mythboxee4\mythboxee.py", line 66, in **init**
00:33:19 T:49436 M:1804816384  NOTICE: self.GetRecordings()
00:33:19 T:49436 M:1804816384  NOTICE:   File "C:\Users\Matthew\AppData\Roaming\BOXEE\userdata\apps\com.erikkristensen.mythboxee4\mythboxee.py", line 175, in GetRecordings
00:33:19 T:49436 M:1804791808  NOTICE: single = [recording.title.encode('utf-8'), recording.subtitle.encode('utf-8'), str(recording.description), str(recording.chanid), str(recording.airdate), str(recording.starttime), str(recording.endtime), recording.getRecorded().watched, x]
00:33:19 T:49436 M:1804791808  NOTICE: AttributeError
00:33:19 T:49436 M:1804791808  NOTICE: :
00:33:19 T:49436 M:1804791808  NOTICE: 'NoneType' object has no attribute 'encode'
00:33:19 T:49436 M:1804791808    INFO: XBPyPersistentThread::Process, iteration started (python)

I am running MythBoxee 4.23.2 beta and MythTV 0.23.1 with fixes through Mythbuntu.

Here is the full log:
http://pastebin.com/av8be9Qn

**Comment by ekristen** [comment]
I am pretty sure this is being caused by some recording not having a subtitle. Can you verify this? Can you look through your recorded table and see if there is anything missing a subtitle?

**Comment by matthewclaussen** [comment]
There are a number of shows that seem to not have a subtitle. Most of them are movies that aired on various networks.

I got this info from the MythWeb interface. Want me to list them all? Look up the blank subtitles some other way?

**Comment by ekristen** [comment]
No need, I just wanted to verify the behaviour. I'll fix it and try and release an update tonight as this seems to potentially be a show stopper.

**Comment by matthewclaussen** [comment]
To add a little more info, I am pretty sure I've had blank show subtitles before and had MythBoxee working. I know this doesn't help much since I can't pin it down to one title but yeah, you are right that it is a show stopper. It's been a problem on my end for a while so please ask if there is any other info you need to know.
Thanks for all the work!

**Comment by ekristen** [comment]
In the meantime, if you weren't having any issues with character encoding you can replace the part of the code that has recording.subtitle.encode('utf-8') with str(recording.subtitle) -- the encode was to fix a non ascii character encoding issue, which seems to have screwed some others now. I'll fix as soon as possible and release an update.

**Comment by matthewclaussen** [comment]
I made that change in the mythboxee.py file and it still seems to be having a problem there.

http://pastebin.com/W8eXU5TK

**Comment by ekristen** [comment]
Unfortunately that is a different error. That is the phantom interface error that seems to plague people at random. It has to do with the mysql library and mysql connection but there hasn't been any consistent data to identify and actual problem yet.

**Comment by matthewclaussen** [comment]
Nuts, let me know if there is any data I can get you if you ever make some progress on it.
Its weird that this problem started on both Boxee computers at the same time.

Would a different Boxee logging level show some more useful info?

**Comment by matthewclaussen** [comment]
Is this the same error that was on Win XP and Windows 7?

**Comment by ekristen** [comment]
Do you know what version you were running before this? 4.x.1.beta? I am assuming you weren't having this interface issue then?

**Comment by matthewclaussen** [comment]
On my Ubuntu box I was running the very first version of 4.xx and then on my Vista box I was running the one right before 4.23.2 beta both ended up with the same problem. 

It might be something with one of the updates for MythTV 0.23.1 from Mythbuntu but these are normal updates that come down the pipe from them, nothing experimental.

**Comment by matthewclaussen** [comment]
Something to add is that everything was working fine 'til I had the mysql connector issue which was before I tried installing some updates to MythTV. I then installed updates thinking it might solve the problem.
I've had this problem for about a month now, didn't take the time to report it 'til now.
