### ISSUE TITLE
Hangs on Loading screen - 4.23.3.beta

### ISSUE THREAD

**Issue by cooper76** [ekristen/mythboxee#12]
I tried out the new version of Mythboxee and it just hangs at the "Loading" screen.

Here is the full log:
http://pastebin.com/xHk8zBRa

**Comment by ekristen** [comment]
This is an Interface Error issue, please add the pastbin.com url to a comment on issue #1. In addition please provide the information requested in the description of issue #1. Would you also be willing to send me a mysqldump of your mythconverg database for testing against?

**Comment by ekristen** [comment]
The reason why I ask you to comment, is so that it is associated with your username and easier to track how many unique cases of this bug I am getting.

**Comment by cooper76** [comment]
I'll send that mysqldump later on.

**Comment by ekristen** [comment]
Actually lets hold off on the mysqldump, I am going to be unavailable starting Friday for a week, after I get back I'd definitely like to get with you and get it as I can't currently duplicate this issue on my Windows XP install.

**Comment by cooper76** [comment]
Not a problem. Just let me know when you are ready.
