### ISSUE TITLE
'ascii' codec can't encode character u'\xf1' in position 141

### ISSUE THREAD

**Issue by matthewclaussen** [ekristen/mythboxee#13]
Since I haven't had any luck with Vista I tried out the latest 4.23.3 beta on my Ubuntu system.
Some good news I have gathered from this is I don't seem to be having the mysql connection error, I guess that is just a problem with Windows systems...

I seem to be having a problem with a character not encoding properly. I tried changing this recording.title.encode('utf-8') to str(recording.title) but no luck.

Here are both logs.
str(recording.title) http://pastebin.com/ukmAMva1
recording.title.encode('utf-8') http://pastebin.com/CXTPwQp0

**Comment by ekristen** [comment]
My guess just by looking at the logs would be that it is the description field throwing the error, can you switch out the str(recording.description) for recording.description.encode('utf-8') and let me know what happens.

Thanks,
-Erik

**Comment by matthewclaussen** [comment]
I switched the two and here is the new log. http://pastebin.com/prMJv63Z

**Comment by matthewclaussen** [comment]
hmm that one pastebin didn't work. I'll post a new one in a bit.

**Comment by matthewclaussen** [comment]
http://mythboxee.pastebin.com/CXhS3ZaV

**Comment by ekristen** [comment]
Try this file ... http://github.com/ekristen/mythboxee/raw/encoding/mythboxee.py

**Comment by matthewclaussen** [comment]
It worked! Did I miss another str(recording.description)?
Not that it matters cause it works!

**Comment by ekristen** [comment]
fixes ascii encoding problem, closed by 812425bfe5c99475b6dee36316548bc2cd8eaf7a
