### ISSUE TITLE
MythTV 0.24 support

### ISSUE THREAD

**Issue by TravellingGuy** [ekristen/mythboxee#17]
Please provide support for the upcoming MythTV 0.24.  MythBoxee presently fails with this:
2010-11-07 19:07:21.000 Python Database Connection: Database schema mismatch: we speak 1254 but database speaks 1264

**Comment by ekristen** [comment]
I'll be adding support as soon as possible, because I will be moving to the 0.24 branch as soon as possible at my house. 

I'll continue to support the 0.23 branch as well when I make the switch.

**Comment by MattsShack** [comment]
Sorry to bother you. I wanted to ask if there was any intension of updating this for mythtv .24? Thank you.

-Matt

**Comment by ekristen** [comment]
Yes I am working on getting my mythtv system back up and running and installing 0.24

**Comment by obrienmd** [comment]
Once you have 0.24 working, will it work against MythTV head?

**Comment by ekristen** [comment]
So I have my system up and running at 0.24, but I am having some difficulties getting the myth bindings to cooperate with python 2.4.6 and the pure python mysql library at this time. Unfortunately I don't know what you mean by MythTV head?

**Comment by MattsShack** [comment]
Any luck on .24? I am not sure how to program for Boxee, but I have a mythtv .24 system running if you need help testing. I just got my Boxee Box yesterday and plan on learning a little more about it this weekend.

-Matt

**Comment by ekristen** [comment]
The Boxee Box is dead, this project is dead.
