### ISSUE TITLE
White (or black) screen, no audio

### ISSUE THREAD

**Issue by rkershenbaum** [ekristen/mythboxee#18]
I've set up MythBoxee (nightly build) to access my MythTV 0.23.1 (MythDora) backend.  I'm using the XML stream method.  I can't use SMB because I have two storage groups.  When I try to play a TV episode on a Windows 7 system, I get only a pure white screen and no sound.  On my Ubuntu system, I get a black screen.  I can play other content in Boxee.  This only happens in Mythboxee.  Is there any other information I can provide to help resolve this?

**Comment by ekristen** [comment]
The Boxee Box is dead, this project is dead.
