### ISSUE TITLE
Additional recordings of the same show do no appear on refresh

### ISSUE THREAD

**Issue by bkdougan** [ekristen/mythboxee#19]
When a new recording of a show that already exists in the MythBoxee cache is found on the backend, it will not update in MythBoxee until one of two things happens

1: A show that does not already exist in the cache (by title) is recorded
2: The app cache is deleted 

This stems from line 251 of mythboxee.py.  Instead of making the fingerprint only by title, it should use more information (either include the subtitle, or switch to something guaranteed to be unique, like recordid).  

I propose changing this line to be
    rectitle = rec.title.encode('utf-8') + str(rec.recordid)

I have made this change to my local copy and it solves the issue.

**Comment by ekristen** [comment]
Awesome, thank you for the code! I'll get this committed soon.

**Comment by ekristen** [comment]
The Boxee Box is dead, this project is dead.
