### ISSUE TITLE
Boxee Box now requires signed applications

### ISSUE THREAD

**Issue by jonmason** [ekristen/mythboxee#20]
After updated to the latest firmware of the Boxee box (1.0.4.17443).  The mythboxee will not load.  Attempts to pull from the repository also fail with an error.  It appears that all non-native apps require that they be signed.

From http://blog.boxee.tv/2011/02/14/netflix-on-the-boxee-box/

Included in this release is a new Application signing process was introduced with this version. If you are hosting your own Applications Repository, or developing applications on the Boxee Box, make sure to sign up at http://www.boxee.tv/developer, and generate the required keys.

If you are a Boxee Box user who is having an issue with an App in an external repository, please contact the developers and inform them of this change.

**Comment by obrienmd** [comment]
Yes, +1 on this functionality. Your app working is a requirement for my purchasing a boxee box!

**Comment by ekristen** [comment]
I'll try and get this signed tonight and put up.

**Comment by ekristen** [comment]
Sorry guys won't be happening until tomorrow. I won't be able to sign the nightly's any more but I am going to release a version for 0.23.1 and sign it. I'll get it added in tomorrow.

**Comment by ekristen** [comment]
Signed and Posted v0.79 support for 0.23.1 only at this time. I am working on 0.24 support.

**Comment by jonmason** [comment]
Awesome, I can launch it now.  Unfortunately, I lost my config after the update and I am having issues configuring it again.

**Comment by ekristen** [comment]
Let me know if you can't get them resolved. None of the config code changed.

**Comment by jonmason** [comment]
It is resolved with the latest build.  Thank you so much for doing this!
