### ISSUE TITLE
Failed to connect to database (same as others?)

### ISSUE THREAD

**Issue by santa8claws** [ekristen/mythboxee#8]
Hi, I just found this project and am very excited about seeing this working for Boxee! I'd like to ask for some help with troubleshooting a failed database connection.

Boxee 0.9.20.12594: WinXP 32bit home 2002 at SP3
MythBackend configured with mythconverg database
MythTV: 0.20.2-168.fc6 

Yes I know it's old, but I haven't found a new version of myth for Fedora 6. Is this the cause of the problem here?

Snippet from Boxee Log:
NOTICE: >>> MythBoxee: def(**init**): Start =========================================================
NOTICE: >>> MythBoxee: def(**init**): Version: 4.0.1.beta
NOTICE: >>> MythBoxee: def(**init**): Python Version: (2, 4, 5, 'final', 0)
NOTICE: >>> MythBoxee: def(**init**): Attempting Database Connection ...
NOTICE: >>> MythBoxee: def(**init**): Error: Failed to connect to database at 'mythconverg'@'mediaserver'for user 'mythtv' with password 'xxxxxx'.
NOTICE: >>> MythBoxee: def(**init**): End ===========================================================

So, what I've done:
1. setup the mythtv backend to allow remote frontends using a non localhost IP
2. checked the mysql permissions with:
     mysql> grant all on mythconverg to mythtv@"192.168.2.%" identified by "<password>";
     Query OK, 0 rows affected (0.03 sec)
     mysql> flush privileges;
     Query OK, 0 rows affected (0.02 sec)
1. tested a "telnet" TCP 3306 connection to the mythtv system which returns this:
     5.0.27'1u{+_!%2,☻mP'p~K<+^{qB
2. checked that myth/mysql remote connections work using windows sqlclient
     Remote command "select user from mysql.user limit 0" returns this error:
     ER_TABLEACCESSDENIED_ERROR(114...

Does mythboxee need access to the user table?

Any help would be appreciated. Thanks!
-- S8C

**Comment by ekristen** [comment]
I've had one other user that had issues connecting to the mysql database either, he had to disable old_password support in mysql. I haven't been able to verify yet, but I think the library I am using (which is implemented entirely in python) doesn't support old_passwords. If you can do that, give it a shot and let me know. I'll keep the issue open until then.

**Comment by ekristen** [comment]
Have you been able to try to disable old passwords? Any help or any new status?

**Comment by santa8claws** [comment]
Yes, that was one of the first things I changed, here's my updated /etc/my.cnf :
<CODE>
[mysqld]
datadir=/var/lib/mysql
socket=/var/lib/mysql/mysql.sock
# Default to using old password format for compatibility with mysql 3.x
# clients (those using the mysqlclient10 compatibility package).
old_passwords=0

[mysql.server]
user=mysql
basedir=/var/lib

[mysqld_safe]
log-error=/var/log/mysqld.log
pid-file=/var/run/mysqld/mysqld.pid
</CODE>

Any other thoughts? Are there any ways to turn on debug messages for the python libraries? Any other log files to check?

Thanks, -- S8C

**Comment by ekristen** [comment]
Post some logs to http://mythboxee.pastebin.com please.

**Comment by ekristen** [comment]
What version of mysql are you using? What version of mythtv? If I don't get a response in the next couple of days I am going to close this issue out.

**Comment by ekristen** [comment]
This has been open too long without action ... closing, it can be re-opened if necessary. But at this point all users of MythBoxee are not reporting any issues with the current version.
